project_id = "rbvbrxjnhmgrtxvwusxr"

[functions.nour-chat]
verify_jwt = false

[functions.analyzeRoom]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.get-order-status]
verify_jwt = false

[functions.export-store-data]
verify_jwt = false
